### ISSUE TITLE
Feature Request: Check if shop is on shopify plus plan so I can include user scopes conditionally

### ISSUE THREAD

**Issue by chandlerwilcox88** [ohmybrew/laravel-shopify#331] opened 2019-09-21 06:13 UTC

**Comment by jedimdan** [comment] 2019-09-23 04:09
Perhaps [this guide in the wiki](https://github.com/ohmybrew/laravel-shopify/wiki/Free-Access-Based-on-Shopify-Plan) is what you're looking for.

**Comment by chandlerwilcox88** [comment] 2019-09-23 07:33
@jedimdan > Perhaps [this guide in the wiki](https://github.com/ohmybrew/laravel-shopify/wiki/Free-Access-Based-on-Shopify-Plan) is what you're looking for.

This is close but a different use case.

Basically, Shopify Plus plans exclusively have the user_read and user_write scopes and regular plans are not allowed so an error pops up when Oauth is initiated.  My app needs to support the user roles for shopify plus plans and regular shops as well.

My solution isn't the prettiest but it is working as of today. Here is what I did:

Added another line to the .env file that is SHOPIFY_API_SCOPES_ENTERPRISE that includes "write_users, read_users". Added a checkbox on the login view for the user to select if they have a shopify plus plan.  Then I added a property called $plan to the ShopifyApp class. After that, I changed the method buildAuthUrl() in AuthShopHandler.php to check if the plan got submitted by the form and if so, then return the different Config::get('shopify-app.api_scopes_enterprise').  I then save it to the database on the shops table after authentication for future lookup.


 I can submit my code for you to see my fix if you'd like but kinda self conscious about my code haha.

**Comment by ohmybrew** [comment] 2019-09-24 00:00
The issue is that we can not poll the shop's info without a token, to get a token from Shopify, they must install.

Thus, we dont know the plan until they install.

I'm not sure what an ideal solution would be for this...

**Comment by chandlerwilcox88** [comment] 2019-09-24 00:03
@ohmybrew I found that out the hard way so I added it to the initial login form to be selected by the user


<img width="847" alt="Screen Shot 2019-09-23 at 4 59 31 PM" src="https://user-images.githubusercontent.com/7296169/65471458-0bd1d280-de24-11e9-987c-cdb35870abef.png">

**Comment by ohmybrew** [comment] 2019-09-24 00:41
The only thing that I could see would help would be some sort of hook system which someone could tie into before and after certain bits of code.. similar to wordpress' add_filter.On Sep. 23, 2019 21:33, Chandler Wilcox <notifications@github.com> wrote:@ohmybrew I found that out the hard way so I added it to the initial login form to be selected by the user

**Comment by chandlerwilcox88** [comment] 2019-09-24 00:46
@ohmybrew 

Ya a hook would be nice!  Here is my manual code changes for the form checkbox above.



**.env**
- added new scopes line for plan
```SHOPIFY_API_SCOPES_ENTERPRISE="read_users,write_users"```


**OhMyBrew\ShopifyApp** 
- added property of plan with a getter/setter

```
    public $plan;

    public function plan($plan)
    {
        
        $this->plan = $plan;

        return $this->plan;
    }
```



**OhMyBrew\ShopifyApp\Traits\AuthControllerTrait;** 
- modified the authenticate method

```
// Get the validated data
        $validated = $request->validated();
        $shopDomain = ShopifyApp::sanitizeShopDomain($validated['shop']);
        $shop = ShopifyApp::shop($shopDomain);

        // Start the process
        $auth = new AuthShopHandler($shop);
        //Check if shopify plus was checked by the user on login
        if (array_key_exists('plan', $validated) ) {
            $auth->plan = $validated['plan'];
        }
        $session = new ShopSession($shop);
        $session->setDomain($shopDomain);
```



**OhMyBrew\ShopifyApp\Models\Shop**
- added plan to fillable

```
protected $fillable = [
        'shopify_domain',
        'shopify_token',
        'grandfathered',
        'freemium',
        'plan_id',
        'namespace',
        'plan',
    ];
```



**OhMyBrew\ShopifyApp\RequestsAuthShop**
 - added plan to ShopifyApp object from form request

```
 public function withValidator(Validator $validator)
    {
        // Determine if the HMAC is correct
        $validator->after(function (Validator $validator) {
            $type = $this->request->get('type', AuthShopHandler::FLOW_FULL);
            if ($type === AuthShopHandler::FLOW_FULL && !$this->request->has('code')) {
                // No code, continue...
                return;
            }
            //Adds Checkbox plan type
            $plan = ShopifyApp::plan($this->request->get('plan'));

            // Determine if the HMAC is correct
            $shop = ShopifyApp::shop($this->request->get('shop'));
            $authHandler = new AuthShopHandler($shop);

            if (!$authHandler->verifyRequest($this->request->all())) {
                $validator->errors()->add('signature', 'Not a valid signature.');
            }
        });
    }

    public function rules()
    {
        return [
            'shop'      => 'required|string',
            'plan'      => 'nullable|string',
            'code'      => 'nullable|string',
            'hmac'      => 'nullable|string',
            'timestamp' => 'nullable|numeric',
            'protocol'  => 'nullable|string',
            'locale'    => 'nullable|string',
        ];
    }
```



**config/shopify-app** 
- added new config to get .env values for enterprise plans
```
    'api_scopes_enterprise' => env('SHOPIFY_API_SCOPES_ENTERPRISE', ''),
```


**OhMyBrew\ShopifyApp\Services\AuthShopHandler** 
- this is where it got messy but in the buildAuthURL method when I added a conditional to check the plan type and which config to send over Oauth


```
public $plan;

public function buildAuthUrl($mode = null)
    {
        // Check if user has checked shopify plus on form
        // Determine the type of mode
        // Grab the authentication URL
        if ($this->plan == 'enterprise') {
            $this->shop->plan = $this->plan;
            return $this->api->getAuthUrl(
                Config::get('shopify-app.api_scopes_enterprise'),
                URL::secure(Config::get('shopify-app.api_redirect')),
                $mode ?? 'offline'
            );
        } else {
            return $this->api->getAuthUrl(
                Config::get('shopify-app.api_scopes'),
                URL::secure(Config::get('shopify-app.api_redirect')),
                $mode ?? 'offline'
            );
        }
    }
```

**Comment by ohmybrew** [comment] 2019-09-28 16:32
Closing as right now... its out of my control, unless someone comes up with an elegant solution.

**Closed by ohmybrew** 2019-09-28 16:32 UTC
Labels: type-question
