### ISSUE TITLE
Builder trashed does not exist when installing shop

### ISSUE THREAD

**Issue by demoskp** [ohmybrew/laravel-shopify#67] opened 2018-08-14 13:20 UTC
I have been getting issues when my app was getting installed and uninstalled and installed again with the token being null and found a similar issue another user submitted and the issue was the new App middleware file so I used that but now I am getting the following issue:

Method Illuminate\Database\Query\Builder::trashed does not exist.

P.S. I updated the package but it seems the new files haven't update so when I updated the App middleware file I did it manually.

**Comment by ohmybrew** [comment] 2018-08-14 19:12
What version are you on? trashed is not something I call directly. I call `withTrashed`.

**Comment by demoskp** [comment] 2018-08-14 19:18
I tried updating and it pulled some of the files and not all, I had to then manually replace the files that were not included and my old files I created myself which got deleted by the update. The issue has been resolved but now I came across another issue which I believe is a bug.

When uninstalling an app and installing it again but declining the charge I get the following error:

Integrity constraint violation: 1062 Duplicate entry '3752820794' for key 'charges_charge_id_unique' 

I believe from what I have checked you try to insert into the database another entry of the same charge id and it all falls over.

**Comment by demoskp** [comment] 2018-08-14 19:56
Still getting the same error.

**Comment by ohmybrew** [comment] 2018-08-14 20:01
I'm getting a new charge ID on post. You manually updated files instead of
composer? Did it update correctly, database too?

**Comment by demoskp** [comment] 2018-08-14 20:06
Yeah I update by running composer install and it picked up all the new packages but for some reason some files did not update so had to update manually. 

The issue now is not when uninstalling and reinstalling, it's when you just decline the charge on the first time.

**Comment by demoskp** [comment] 2018-08-14 20:07
Yeah I did update the database and the migrations too.

**Comment by ohmybrew** [comment] 2018-08-14 20:12
I'll do a fresh install and test this but it's strange for sure.

**Comment by demoskp** [comment] 2018-08-14 20:17
I think the reason I am getting the error and you're not is because instead of:

if ($status === 'declined') {
            // Show the error... don't allow access
            return abort(403, 'It seems you have declined the billing charge for this application');
        }


I return a view letting them know what has happened because this shows an error if you don't.

**Comment by demoskp** [comment] 2018-08-14 20:17
I mean it's a requirement by shopify.

**Comment by demoskp** [comment] 2018-08-14 20:54
One more thing to note is that say they don't decline and then uninstall the app and reinstall it later, it wont ask them to agree the charges again which would be an issue. right?

**Comment by demoskp** [comment] 2018-08-15 16:10
Any update on this one?

**Comment by ohmybrew** [comment] 2018-08-16 13:39
Currently no. I installed, had a test charge, uninstalled, re-installed, had a new charge, I did not get the same ID back. I can't reproduce this issue right now.. but I'll keep trying a few more things to be sure, I'm wondering if your modifications are somehow affecting it, but I can't say for sure yet.

**Comment by demoskp** [comment] 2018-08-16 14:47
Change the return error with returning a view and you'll get the error. No need to uninstall and install again, just decline the charge.

On 16 Aug 2018 2:39 p.m., Tyler King <notifications@github.com> wrote:

Currently no. I installed, had a test charge, uninstalled, re-installed, had a new charge, I did not get the same ID back. I can't reproduce this issue right now.. but I'll keep trying a few more things to be sure, I'm wondering if your modifications are somehow affecting it, but I can't say for sure yet.

**Comment by ohmybrew** [comment] 2018-08-16 14:58
Oh I get it... I think I see the issue, the code is not marking the charge as declined (for the database) but Shopify is. I believe adding this  `$charge->status = 'declined';` to line 67 of Traits/BillingControllerTrait may fix the issue. I'll code this in and test it out hopefully tonight..

**Comment by ohmybrew** [comment] 2018-08-17 15:57
I've implemented the above @demoskp in the latest release, should solve the issue.

**Comment by ohmybrew** [comment] 2018-08-22 19:26
Code is in next release (this) week, that plus using a method like: https://laravel.com/docs/5.6/errors#custom-http-error-pages

Should produce a nice page. Closing for now.

**Closed by ohmybrew** 2018-08-22 19:26 UTC
