### ISSUE TITLE
Extend Billable App

### ISSUE THREAD

**Issue by pearlbells** [ohmybrew/laravel-shopify#316] opened 2019-08-20 09:25 UTC
Hi,

I have used this package for creating a Shopify app and added subscription plans.

Please direct me on how to extend the billable section. I need to disable the upgrade button-based the shop_id and plan_id from the charges table. ( disable the upgrade option if they already paid or in a plan)

Thanks in advance
Pearl

**Comment by Kyon147** [comment] 2019-08-20 13:36
Hi @pearlbells 

If you are talking about the Shopify screen where they see details on the new plan and need to accept it, you won't be able to disable anything.

This billing screen is actually hosted on Shopify itself, the app just makes a redirect with the correct parameters.

You'd be better off putting in some limit on your side i.e in the app through middleware etc but depends on how you are using it.

**Comment by ohmybrew** [comment] 2019-08-20 17:58
Hi @pearlbells 

You need to manually poll the database to find out what plan the shop is on to show or hide the button.

$shop = ShopifyApp::shop();
$currentPlan = $shop->plan; // do what you need to do here to determine to show or hide.

I'm currently pretty swamped, as this is not a bug, I am closing for now, if you feel this is a bug please reopen.

**Closed by ohmybrew** 2019-08-20 17:58 UTC
