### ISSUE TITLE
Get stuck on infinite redirects to `/authenticate/partial`

### ISSUE THREAD

**Issue by darrynten** [ohmybrew/laravel-shopify#289] opened 2019-07-23 07:42 UTC
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The application should not get stuck in a redirect loop between the configured application URL and the `/authenticate/partial` route.

## Current Behavior

The app enters an infinite 302 redirect loop

## Failure Information

Bounces between

`/?hmac=XX&shop=XX` and `/authenticate/partial?shop=XX` with 302s until the browser stops the redirections

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Make a new app and demo shop
2. Configure redirect URL in .env to `/authenticate/full`
3. Create a test plan that is billable and has 0 days free trial
4. Set session and cache driver to redis
5. Make the default URL `/` and add the `auth.shop` and `billable` middlewares to the welcome route
6. Try to add the new app to the new demo shop

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v9.0
* Laravel Version: v5.8.29
* PHP Version: v7.3.6
* Using a toolset (Docker, Laradock, Vagrant, etc.): None

### Failure Logs

Apache logs show redirects as detailed above

**Comment by ohmybrew** [comment] 2019-07-24 15:44
Thank you for the report. I wouldn't add /full to the URL, let the code handle that.

However, I've setup Laravel v5.8, Laravel Shopify v9.0, Redis for session/cache, with a plan that has no trial.

Result: https://streamable.com/ejjrq

Any other tips I can try out?

**Comment by darrynten** [comment] 2019-07-25 05:14
I've downgraded to 8.0.0 for the app in question and am in the process of publishing it.

I will be sure to start a fresh app directly after submitting the app store listing and will use the latest version on a fresh install.

I'll take notes during the process and update here as soon as I have more information.

FYI the behavior exhibits over ngrok, should have mentioned that earlier :)

**Comment by ohmybrew** [comment] 2019-07-25 13:52
Ah ngrok. Many people have had issues in the past with ngrok from webhooks to install issues. I bet thats the issue here :(

**Comment by diemah77** [comment] 2019-07-26 14:27
I can also confirm the "too many redirects" issue: when the shop is removed from the database, but is still in the session.

The other away around I am redirected to the login page.

**Comment by StefanNeuser** [comment] 2019-07-26 14:28
@diemah77 and @ohmybrew i guess that this issue will also appear when somebody wants to use the app between multiple/different shopify stores because the session_domain will stay the same like app.example.com .. or i'm wrong?

**Comment by ohmybrew** [comment] 2019-07-26 15:15
Oh this happening when Removed from database and try to access? Ah I can work on that if that's the issueOn Jul. 26, 2019 11:57, diemah77 <notifications@github.com> wrote:I can also confirm the "too many redirects" issue: when the shop is removed from the database, but is still in the session.
The other away around I am redirected to the login page.

**Comment by diemah77** [comment] 2019-07-26 15:27
I am not sure whether this is the only scenario leading to too many redirects. 
One of our apps is currently being reviewed by Shopify. And this issue appears when they try to access the app preventing them from testing.

**Comment by StefanNeuser** [comment] 2019-07-26 15:30
Hi @ohmybrew,

what the Shopfiy-Review Team was telling me a couple of minutes ago is:

```
Hey Stefan,

Unfortunately this was tested across two different browser incognito sessions and we're still seeing the error. See screenshot. (https://screenshot.click/26-59-c7q7k-rs256.png)

Please ensure you are testing your app in a live environment prior to following up.
```

I ask them about the Browser. @diemah77 and me can only reproduce it when the database has no entry but the session is filled.

In incognito-browser-session there should no session alive. We are using `file` driver for the session. Maybe Laravel detects a session also in incognito-browser-session for `file` session driver. We are thinking about to switch to `cookie` driver instead because i know that in incognito-browser-session no cookies are present.

What do you think?

**Comment by ohmybrew** [comment] 2019-07-26 16:03
Database - no entry.
Session - filled.

Ok well this is a senario I'll have to fine-check for in the middleware and send to a full auth.

**Comment by StefanNeuser** [comment] 2019-07-28 20:08
> Database - no entry.
> Session - filled.
> 
> Ok well this is a senario I'll have to fine-check for in the middleware and send to a full auth.

i guess this https://github.com/ohmybrew/laravel-shopify/pull/291 also solves this issue because we need a full auth instead of a partial.

**Comment by StefanNeuser** [comment] 2019-07-28 20:18
hi @ohmybrew can you please explain what is the difference between 
`AuthShopHandler::FLOW_FULL` and `AuthShopHandler::FLOW_PARTIAL` ? In most cases full makes really sense. 

And can you please explain what is the difference between `SHOPIFY_API_GRANT_MODE=per-user` and `SHOPIFY_API_GRANT_MODE=offline` i dont get it :)

First i thought https://github.com/ohmybrew/laravel-shopify/pull/291 is also the solution for the redirect loop but it isnt :)

You will always end in a redirect loop for 

```
Database - no entry.
Session - filled.
```

when you make not a full auth.

**Comment by ohmybrew** [comment] 2019-07-28 20:47
HeyOffline mode is standard for most app, grabs a token which can be used forever and stored in database.Peruser is a mode which has a token per staff member who accesses the app.So full is where a complete redirection to Shopify's oauth screen is required. Either due to mismatching shops, a brand new shop, no token, per user mode, etc.Partial happens when offline mode is enabled (default), the shop session expired but still existing in database with a valid token, it simply updates the session preventing page flashes as seen before with only a full flow.On Jul. 28, 2019 17:18, Stefan Neuser <notifications@github.com> wrote:hi @ohmybrew can you please explain what is the difference between
AuthShopHandler::FLOW_FULL and AuthShopHandler::FLOW_PARTIAL ? In most cases full makes really sense.
And can you please explain what is the difference between SHOPIFY_API_GRANT_MODE=per-user and SHOPIFY_API_GRANT_MODE=offline i dont get it :)
First i thought #291 is also the solution for the redirect loop but it isnt :)
You will always end in a redirect loop for
Database - no entry.
Session - filled.

when you make not a full auth.

**Comment by ohmybrew** [comment] 2019-07-29 02:51
I have pulled in a PR from @StefanNeuser and will be testing master branch with some scenarios to ensure it works to fix this bug.

**Comment by StefanNeuser** [comment] 2019-08-01 07:35
Any updates here?

**Comment by ohmybrew** [comment] 2019-08-01 12:58
I'm swamped with work. Trying to get to it :)On Aug. 1, 2019 03:35, Stefan Neuser <notifications@github.com> wrote:Any updates here?

**Comment by StefanNeuser** [comment] 2019-08-01 13:41
Hi @ohmybrew , i found another issue so there is still a bug that i will resolve. 

<img width="997" alt="Screenshot 2019-08-01 at 15 40 53" src="https://user-images.githubusercontent.com/2176503/62298218-e1dae000-b472-11e9-910b-e3d216de5ca3.png">

**Comment by ohmybrew** [comment] 2019-08-03 16:58
#293 in place. Seems to solve each case in physical tests I've performed.

**Comment by ohmybrew** [comment] 2019-08-07 13:21
I will be pushing a release out for this in the evening as I see no blockers right now... unless I'm missing a situation to physically test.

Did all testing with file storage for session backend and redis for a session backend.

```
Test: Shop is brand new, does not exist
Expected: Redirect to install process. Full redirect.
Result: Success

Test: No existing session
Expected: Session created and HMAC validated.
Result: Success

Test: With existing shop in session, try to load app in a different shop
Expected: Since shops do not match, session must be updated. No full redirect.
Result: Success

Test: With existing shop in session, try and load app (admin link) in a different shop
Expected: Since shops do not match, session must be updated. No full redirect.
Result: Success

Test: Shop which is trashed, try and load app.
Expected: Full-page redirect to auth flow to un-trash the shop.
Result: Success
```

**Comment by diemah77** [comment] 2019-08-07 13:23
Much appreciated!

**Comment by ohmybrew** [comment] 2019-08-08 16:52
[Released](https://github.com/ohmybrew/laravel-shopify/releases/tag/v9.1.0). I hope this fixes your issues...

**Comment by ohmybrew** [comment] 2019-08-12 01:20
In testing [v9.1.0](https://github.com/ohmybrew/laravel-shopify/releases/tag/v9.1.0) with several contributor changes, all seems well.
Added a Blade helper as well to help out (see usage).
Re-Open if any issue persists after updating

**Comment by Kyon147** [comment] 2019-08-19 13:24
The issue with the infinite redirects came up for me when trying to install the app for the first time. It sends you to /partial and comes up with a redirect error.

**Comment by ohmybrew** [comment] 2019-08-19 13:38
The problem is, I can't detect a decline on install or charges... theres no documentation from Shopify to my knowledge about this.

**Comment by Kyon147** [comment] 2019-08-19 13:39
Can I disable this partial flow for the time being somehow?

**Comment by ohmybrew** [comment] 2019-08-19 14:03
Its not able to be disabled, I would need a way to know it was from a cancellation. I will have to hunt for a hint on what to do in this case but unfortunately its more a shopify issue than my issue.

If someone we're to decline a charge or install, it would be nice if shopify sent some sort of status with the request. It did not for the past couple years but that may have changed and I'll double check.

If nothing is sent, then the only way is to do some hacky work around which I will not implement.

I'll let you know what I find...

**Comment by ohmybrew** [comment] 2019-08-19 14:19
@Kyon147  We've had a nice few changes on the master branch from several contributors but I think this is outside the issue.

In testing "cancel", Shopify simply redirected to /apps in the Shopify admin, it doesn't do any authentication loops, it completely backs out of the app. Any more information you can provide?

**Comment by Kyon147** [comment] 2019-08-19 15:00
I think what I can see is this.

1. User installs the app, then on the accept page clicks "cancel", this then pushes them back out.
2. In the DB though at this point, you insert a row
3. User tries to reinstall because of the auth.shop middleware sees a DB entry it tries to do a partial auth flow and because the install and session are incomplete I think it causes the redirect infinitely. 

Even though the shop was not installed, I manually added a delete_at date but left the token null. This worked because the app then does a full authenticate.  

You seem to have a bug in the partial flow somewhere.

**Comment by Kyon147** [comment] 2019-08-19 15:09
@ohmybrew I've also tried to debug it and going to install on a new store and then cancel and try and reinstall this come up.

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Argument 2 passed to OhMyBrew\BasicShopifyAPI::setSession() must be of the type string, null given, called in \ohmybrew\laravel-shopify\src\ShopifyApp\Traits\ShopModelTrait.php on line 87"

**Comment by Kyon147** [comment] 2019-08-19 15:21
@ohmybrew I've been debugging it and there is something up with the validateShop and HandleBadSesson

On line 70 in AuthShop I changed this to always return flow_full and it works, if the user first time does not install.

```
            $flowType = $session->isType(ShopSession::GRANT_PERUSER) ?
                AuthShopHandler::FLOW_FULL :
                AuthShopHandler::FLOW_FULL;
```

However, the partial flow does not work in the instance where the user does not install the app the first time they are present with it. (On a fresh store only).

**Comment by ohmybrew** [comment] 2019-08-19 15:25
Hmm yeah it should do a full authenticate if token is missing.

I think this is solved in master. Several people have contributed to changes for auth flow the past week.

In testing this case:
1. Go to install app
2. Click cancel
3. Attempt to re-install app

In the above for master, all works fine, no issues with looping or partial flow. So I suspect next release it should resolve. I just mentioned earlier today that I plan to do a release later tonight when I confirm a few more things, so this may fix the issues. @Kyon147

**Comment by Kyon147** [comment] 2019-08-19 15:48
Oh so v 9.0.1 might have the bug in it but a new release tonight should solve that?

Good to know, will keep an eye out.

I'm starting to get a better understanding of how your package works, so would love to help you with issues through PR in the future as this is such a good package. @ohmybrew

**Comment by ohmybrew** [comment] 2019-08-19 20:08
@kyon147 Yes the above scenario for reinstall works fine in master so I suspect the patch release will work fine for your issue.

**Comment by StefanNeuser** [comment] 2019-08-20 08:56
@ohmybrew and @Kyon147 for me the current master is not fixing the infinite loop issue when i install the app via the app-installation-button. You can simulate the app-installation-button from the appstore in you dev-stores describe as here https://help.shopify.com/en/api/app-store/listing-in-the-app-store/testing-your-app-before-submitting#installing-a-free-app-on-a-development-store 

if i reinstall the app served by my webserver i get this partial auth infinite issue. The shopify team pointed this out to me several times. 

Now i disabled partial auth in my fork and this issue is also solve.

So my question is, why do we make use of that partial-auth? It seems to be broken.

**Comment by ohmybrew** [comment] 2019-08-20 14:21
To prevent the page flashing and sending data twice.

Well if this is the case, the check for the token existing is not working properly because if it were, it would fwd you to the full auth process... I'll dig into this some more.

**Comment by ohmybrew** [comment] 2019-08-23 14:27
v9.2.0 is out which hopefully should fix the issues everyone's faced.
Thats everyone for the contribs.

**Comment by StefanNeuser** [comment] 2019-08-24 07:01
Hi @ohmybrew , i want to try it out on our sandbox system to see if it fix the partial out issue. Thank you for the release

**Comment by StefanNeuser** [comment] 2019-08-24 09:51
Hi @ohmybrew ,

i took a look into all changes but i can find some changes that points to the issue with partial auth

> if i reinstall the app served by my webserver i get this partial auth infinite-loop issue. The shopify > team pointed this out to me several times.
> Now i disabled partial auth in my fork and what fixed this issue.
> So my question is, why do we make use of that partial-auth? It seems to be broken.

Did you changed something in the api package to fix that?

**Comment by ohmybrew** [comment] 2019-08-24 13:40
I did not yet include a check for the dev store stuff. It seems checking if the token is empty is somehow broken, as its not seeing it and sending them to a full flow.On Aug. 24, 2019 04:31, Stefan Neuser <notifications@github.com> wrote:Hi @ohmybrew , i want to try it out on our sandbox system to see if it fix the partial out issue. Thank you for the release

**Comment by ohmybrew** [comment] 2019-09-06 04:07
V10 is out which should solve the issues we've faced thanks to everyones contributions. Partial flow is also removed for the meantime and only full flow now.

Since the original issue is cleared by removing partial flow, I am closing this for now. Any future issues related to auth, please open a new issue :)

**Closed by ohmybrew** 2019-09-06 04:07 UTC
Labels: status-in-progress, type-bug
