### ISSUE TITLE
AuthShop middleware needs to handle exceptions gracefully

### ISSUE THREAD

**Issue by ncpope** [ohmybrew/laravel-shopify#327] opened 2019-09-03 08:06 UTC
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

If the shopify_domain is not set on a route protected by the auth.shop middleware there should either be a redirect to the /login route or a specific exception thrown.

## Current Behavior

Currently there is just a general Exception being thrown.

### Steps to Reproduce

See my repo where I followed installation steps: https://github.com/ncpope/tester/commits/master

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: ^9.2
* Laravel Version: 5.8.*
* PHP Version: PHP 7.3.4
* Using a toolset (Vagrant):

### Failure Logs

<img width="1664" alt="Screen Shot 2019-09-03 at 10 58 50" src="https://user-images.githubusercontent.com/1903724/64154589-dc8a0000-ce39-11e9-97ad-4f7ac3af9ba6.png">

**Comment by ncpope** [comment] 2019-09-03 08:13
Nevermind, I was using an outdated version of the package. Closing....

**Comment by jedimdan** [comment] 2019-09-04 07:06
Hi @ncpope, which version did you get to that resolved this problem? I'm on 9.2 and it's still throwing this exception for me. From what I can see, `AuthShop` will still throw an exception when there's no shopify domain, and this exception isn't caught anywhere.

**Comment by ncpope** [comment] 2019-09-04 12:42
@jedimdan you're right, I just took a quick glance yesterday as I ran into the bug on a new projects using 9.2.0 and I assumed that the changes would somehow handle redirecting to the `/login` route. The current behavior of throwing an exception is not ideal as the middleware will just fail with an unhandled exception being thrown.

https://github.com/ohmybrew/laravel-shopify/blob/554a121983e7f3af8c79d5e3e34a0b928f09b34c/src/ShopifyApp/Middleware/AuthShop.php#L136

As far as I can tell I don't see a reason for this line to throw an exception. I think it should just redirect to the `/login` route.

I am going to re-open this issue to encourage discussion. Any clarification behind this would be appreciated.

**Comment by StefanNeuser** [comment] 2019-09-04 18:00
Hi @ncpope i really understand your issue i thought about the same. What you can do for now is listening in `App\Exceptions\Handler` for  the `MissingShopDomainException` or other Exceptions. 

You can check it with `if( $exception instanceof ...)` in the render method and redirect or return with some output. 

Hope this helps

**Comment by jedimdan** [comment] 2019-09-05 01:01
@StefanNeuser that's a good suggestion. Seeing that the exception is being changed into a specific `MissingShopDomainException` in `master` now (the latest release throws a generic Exception), I'm guessing the decision to throw an exception was deliberate? Was trying to find a discussion regarding the rationale behind the throwing of an exception instead of handling it to better understand where this is going.

**Comment by ncpope** [comment] 2019-09-05 08:16
@StefanNeuser I like the idea behind being able to catch the Exception and then being able to choose how you handle it.

My issue is that I think that it should default to redirecting to the `/login` route. I think this is critical functionality out of the box.

If the developer then wants they can extend the package in some way to customize it to fit their needs.

**Comment by ohmybrew** [comment] 2019-09-06 04:05
Is there something built-in Laravel that can catch it and let the developer do what they want this way?

I like how you can define 404.blade.php etc, is there a way to do this with standard exceptions?

**Comment by ohmybrew** [comment] 2019-09-06 04:10
Ooops, closed it by mistake. Labeling with need-help as I'd like some external suggestions :)

**Comment by jedimdan** [comment] 2019-09-06 07:55
Yes there is. I believe you can do that with the ‘render’ method in the [exception handler](https://laravel.com/docs/6.0/errors#render-method). I’ll only be back at my computer next week to test that out though.

I guess the options are to have a default behavior for the package that can be tweaked by the config file (for example, a flag to decide whether to throw an exception or to redirect to login), or to just throw the exception and document it in the installation notes?

**Comment by jesephan** [comment] 2019-09-06 17:38
Im in favor of additional value to config file on handling missing shopify_domain. Some wanted to redirect to login page and some wanted to throw an exception and then catch it.

**Comment by ohmybrew** [comment] 2019-09-06 19:03
If it can be handled solely through stock laravel, then no configuration would be needed inside the package, which is what I'm trying to dig into.

Because if it can be handled by laravel, the package would simply throw an exception like normal. If a developer wants to redirect to the login screen with a flash message, they could use the render items... looking into it.

**Comment by ohmybrew** [comment] 2019-09-07 14:49
Ok so I am thinking:

Add a render method to these new exceptions which points to a basic styled view (something like the login page).

This way, someone can easily override the view inside Laravel and do what they wish.

**Comment by StefanNeuser** [comment] 2019-09-07 14:53
@ohmybrew otherwise you can do something like a did here: https://github.com/ohmybrew/laravel-shopify/pull/320

**Comment by ohmybrew** [comment] 2019-09-07 14:54
Yup!

**Comment by ncpope** [comment] 2019-09-09 13:56
@ohmybrew thanks I think that's a great solution

**Comment by darrynten** [comment] 2019-09-11 05:43
I never expected the `shop_domain` to be missing.

I've been trying to reproduce but am unable to.

**Comment by jedimdan** [comment] 2019-09-11 06:07
@darrynten the `shop_domain` isn't set if the app isn't launched from Shopify itself. For example, if you go to the root of the app before the app is logged in.

**Comment by Kyon147** [comment] 2019-09-11 10:45
@ohmybrew 100% agree. You also use it through Shopify would be unable to do so anyway as by default they would pass your through /auth

Any other route in the app would be behind auth.shop so not sure this is an issue you'd need to fix.

We have admin section on apps outside auth.shop but it doesn't go through auth so never looks for the token, so that also should not be an issue.

**Comment by StefanNeuser** [comment] 2019-09-11 10:53
Hi all,

we are often call the app outside the shopify context but we do this only for local dev. 

In order for this to work, you must first open the app from shopify, then the shop will be recognized via the laravel session. There's the `$shopDomainSession = $session->getDomain();` in AuthShop.php

**Comment by Kyon147** [comment] 2019-09-11 10:55
@StefanNeuser if you are local testing, could you not just use an ssh tunnel like Ngrok? Then you will also be in Shopify context?

**Comment by StefanNeuser** [comment] 2019-09-11 10:56
@Kyon147 that doesnt matter in this case. i prefer using http://localtunnel.me

**Comment by Kyon147** [comment] 2019-09-11 11:03
@StefanNeuser just trying to understand the need to be outside Shopify context for local development to understand the issue. Can you give an example?

**Comment by jedimdan** [comment] 2019-09-11 13:06
Ahhh ok I think I get it now. 

We are working on our first app and have yet to submit to Shopify, that’s why so far we’ve been sending people to the root of our production app to install it to their store. But if it was on the Shopify App Store (which is the goal for everyone anyway) then you’re right. It’s quite unlikely that the app would ever not go through Shopify. 

In other words, what you guys are saying makes sense, and i now get why the decision was made for it to throw an exception.

**Comment by ohmybrew** [comment] 2019-09-11 13:13
Going to the install page should be fine, not sure I follow the missing shopify_domain issue :(

**Comment by jedimdan** [comment] 2019-09-11 13:26
Maybe I can share my app as an example. 

Right now, in order to install my app, merchants will go to example.com since its not yet available from the Shopify App Store. Since it’s not going through shopify, there is no auth of any form. In this scenario, when someone enters example.com in their browser, there’s no shopify_domain, and thus the exception is thrown. 

But of course, as it turns out, this scenario wouldn’t be common. For those of us who want to use this scenario, I think it would be fine if we just handled the exception ourselves.

**Comment by Kyon147** [comment] 2019-09-11 13:28
@jedimdan for example.com are you behind the `auth.shop` middleware as your example should push you over to the "login" page.

**Comment by ohmybrew** [comment] 2019-09-11 13:34
The "install" (/login) route is not behind `auth.shop` by default, you should not receive an error there.

It should direct you to /authenticate (which is behind `auth.shop`).

**Comment by jedimdan** [comment] 2019-09-11 13:37
@Kyon147 yes as per the [installation instructions here](https://github.com/ohmybrew/laravel-shopify/wiki/Installation#routing), `auth.shop` is on the `/` route. 

`auth.shop` used to redirect to the "login" page at that route until this commit: https://github.com/ohmybrew/laravel-shopify/commit/220a2022477862a2e6b28d0cdfcf5098b255f7b9#diff-2076f8eabfc1bddef91ca9ecda1dbbefR105 was introduced in v9.2. Which is why this issue was raised.

@ohmybrew you are right that install is not behind `auth.shop`, but `/` is. The problem we are facing is that `/` didn't use to throw an exception. It used to redirect to `/login`.

**Comment by Kyon147** [comment] 2019-09-11 13:47
@jedimdan that is my bad - I am still using v9 for my live apps so not seen this issue.

I see the issue now and looking at the code, it seems like all the if statements are always looking for a Shopify side condition because of the sanitizeShopDomain().

@ohmybrew did mention adding a render method, which can be adjusted to suit the needs of each developer which makes sense. As you could just create your own redirect to login if you wanted that user flow.

Personally, a default redirects to log in makes sense in my head but might not work for everyone. Not sure the exact reason for the change.

**Comment by ohmybrew** [comment] 2019-09-11 13:47
Okay that makes more sense... yes I am thinking about plugging in a render method as default to redirect to /login with a session message. I am exploring this tonight :)

**Comment by jedimdan** [comment] 2019-09-11 13:52
@ohmybrew Cool! Will be happy to help test. Since we are working on a new app that's not yet published, we've been trying to get to all the latest versions of our dependencies so that we can have a bit more runway by the time we publish, so we're more willing to be on the bleeding edge.

**Comment by jedimdan** [comment] 2019-09-12 03:10
I just began using a bug reporter for my app (trying our [FlareApp.io](https://flareapp.io/) cos it's designed specifically for Laravel and is built into Laravel 6), and realised that in addition to the error handler, I also need to add the exception to the `$dontReport` list as per the [Laravel docs](https://laravel.com/docs/6.0/errors#report-method). If not it'll still keep showing up in error reporters.

**Comment by StefanNeuser** [comment] 2019-09-12 06:38
> @StefanNeuser just trying to understand the need to be outside Shopify context for local development to understand the issue. Can you give an example?

chrome dev tools, performance (speed), more screen, xdebug

**Comment by bmadigan** [comment] 2019-09-14 00:17
I have a hack fix that I'm using:
```
Laravel v6.0.3
HomeMybrew: ^10.0
Valet: 2.2.2
```
I used the following:
```
        if ($exception instanceof MissingShopDomainException) {
            return response()->view('auth.login');
        }
```
in the `handler > render` function and it's working for me as of now.

**Comment by ohmybrew** [comment] 2019-09-24 00:03
I am going to implement the handle/render function and sniff the current app env to know weather to skip it (show exception as is) or show the redirect.

Redirect => on production
Exception => on development

I'll push a PR in later tonight for this.

**Comment by ohmybrew** [comment] 2019-09-28 16:31
Closing per release v10.1.0 [example](https://i.imgur.com/oHIzlSD.png).

Now redirects (if in production) to login route, with error listed, for both signature exception and domain exception.

**Closed by ohmybrew** 2019-09-28 16:31 UTC
Labels: status-in-progress, type-feature

**Comment by jedimdan** [comment] 2019-10-01 05:34
@ohmybrew I just tried v10.1.0, and the problem is that I have several environments outside of `local` or `testing`, such as `staging`, `sandbox` etc. I know this is how the environment is supposed to be used because that's how Ignition differentiates environments in error logging, for example.

So I feel that the app environment is not the right config to decide whether to redirect or throw an exception. May I propose that we use the `app.debug` flag instead?

So like
```php
if(config('app.debug')) {
```

Instead of 
https://github.com/ohmybrew/laravel-shopify/blob/b6dde2f935c6ede7ee555b465c9a5f902b571cc5/src/ShopifyApp/Exceptions/BaseException.php#L26

**Comment by jedimdan** [comment] 2019-10-01 05:37
That said, I'm still not really sure I understand why these two scenarios shouldn't always be handled. Is it so that we know during development that there was a problem in our setup in ordinary scenarios?

**Comment by ptcampbell** [comment] 2019-11-05 05:07
In my case I have an embedded / standalone app hybrid for development purposes. I think I agree with @jedimdan that we should redirect.
